version: "3.9"

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
    command: node --watch app.js
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
